### ISSUE TITLE
Unsure on config

### ISSUE THREAD

**Issue by benjam-es** [serverfireteam/efinance#1]
Hi,

I have tried adapting Ben Griffiths code and keep coming up with an error

```
SOAP-ERROR: Parsing WSDL: Couldn't load from 'https://ibarclaysurlhere' : failed to load external entity
```

I have since found this repo. But i'm unsure of what is supposed to be set in the config and where the .wsdl file is in the repo that is mentioned in step 6.

**Comment by quant-algo** [comment]
@benjam-es  upload your wsdl file in  storage\app and name of file should be efinance.wsdl .

Let me know if you need more help , My mail , support[a]serverfire.net

**Comment by benjam-es** [comment]
Hi, 

Thank you for the quick response

Where do I get the wsdl file from?
